- name: install dependencies
  become: true
  apt:
    name: ["nodejs", "npm", "tar"]
    state: latest
    update_cache: yes

- name: copy backend folder
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: node build
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
    npm run prestart:prod

- name: start server
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name app -- start